// Generated by CoffeeScript 1.6.3
(function() {
  var MarkovPrediction;

  MarkovPrediction = (function() {
    function MarkovPrediction() {
      this.markov = new MarkovChain;
      $("#input").keyup(this.handleKeyup.bind(this));
      $('#input').change(this.handleChange.bind(this));
    }

    MarkovPrediction.prototype.handleKeyup = function(event) {
      var entity;
      entity = String.fromCharCode(event.keyCode);
      this.markov.process(entity);
      return this.predict();
    };

    MarkovPrediction.prototype.handleChange = function(event) {
      var $textarea;
      return $textarea = $(event.target);
    };

    MarkovPrediction.prototype.predict = function() {
      var _ref;
      return $('#prediction').html((_ref = this.markov.predict()) != null ? _ref.join('') : void 0);
    };

    return MarkovPrediction;

  })();

  window.MarkovPrediction = MarkovPrediction;

}).call(this);
